/*
    Project 1b
    Author: Shaan Arora, C3236359
    A1 Class
        Main driver for the entire lexical analyser/scanner
        Creates a single Scanner object which will run the scanner
        Hopefully outputs all found tokens and all lexical errors
*/

public class A1
{
    public static void main(String[] args)
    {
        assert(args.length != 1) : "File name required";
        String fileName = args[0];
        LexicalScanner lexical = new LexicalScanner();
        OutputController oc = new OutputController();
        //Read the file with the file name that was given in the program arguments
        lexical.readFile(fileName);
        //Set the input of the OutputController to the file/input that the LexicalScanenr object generated
        oc.setInput(lexical.getInput());
        //Output all Token objects generated by the LexicalScanner object
        oc.outputLexicalScanner(lexical);
        //Pass to the OutputController object the ArrayList of Token objects generated by the LexicalScanner object
        oc.setTokenStream(lexical.getStream());
        //Generate a listing file which is a copy of the input file except that each line will start with its its line number
        //  and all errors found will be written at the end of the file with their respective line numbers
        oc.generateListingFile("listing.txt");
        System.exit(0);
    }
}